export const urlCandidates = "http://localhost:3333/api/candidates"
export const urlCompanies = "http://localhost:3333/api/companies"
export const urlReports = "http://localhost:3333/api/reports"
export const urlUsers = "http://localhost:3333/api/users"
export const urlLogin = "http://localhost:3333/login"